"""delete_user_id_column_from_exercises_table

Revision ID: f4e394068e35
Revises: f87234fe4156
Create Date: 2026-06-13 17:01:49.520050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4e394068e35'
down_revision: Union[str, Sequence[str], None] = 'f87234fe4156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_user_id'), table_name='exercises')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_exercises_user_id'), 'exercises', ['user_id'], unique=False)
    # ### end Alembic commands ###
